spring:
  application:
    name: blogcms
  datasource:
    url: jdbc:h2:mem:blog_db
    username: sa
    password: secret
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update